version: '3.8'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - 3308:3306
    networks:
      - milenio-network

  api:
    container_name: milenio_api
    restart: always
    image: milenio-backend
    build: ./server
    ports:
      - 8080:8080
    networks:
      - milenio-network
    depends_on:
      - "db"

networks:
  milenio-network:
    driver: 'bridge'