version: '3.8'

services:
  db:
    container_name: milenio_db
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3308:3306

  api:
    container_name: milenio_backend
    restart: always
    image: milenio-backend
    build: ./server
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: root
      MYSQL_HOSTNAME: db
      MYSQL_PORT: 3306

    ports:
      - 8080:8080
    volumes:
      - ./server:/app
    depends_on:
      - "db"
